#DEFINE OTHERDIC "XX3|XXC|XAB|XXJ|XXE|XXP|XXX|XXY|XXZ|XA2|XA5|XA6|XA7|XA8|XA9|XAA|XB2|XA3|XA4|XA1|XXH|XXT|XXB"
#DEFINE DICFWOPEN "XX4|XX6|XX7|XXD|XXF|XXV|XXC|XAB|XB0"
#DEFINE NOSYSTEMLOAD "SX4|SXK|SXO|SXP|SXT|SX0|SXU|SXV|SXH|SXI|XX0|XX1|XX2|XX5|XXC|"
#DEFINE DICMPSYSOPENTABLE "SX4|SXK|SXO|SXP|SXT|SX0|SXU|SXV|SXH|SXI|XX0|XX1|XX2|XX5|XXC|XB4|XB5|XX4|XX6|XX7|XXD|XXF|XXV|XXC|XAB|XB0"

